<%@ Page Language="C#" AutoEventWireup="true" CodeFile="SqlDataTest.aspx.cs" Inherits="SqlDataReaderTest" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>[Test] SqlData</title>
	<link rel="stylesheet" type="text/css" href="~/Styles/custom.css" />
</head>
<body>
    <form id="form1" runat="server">
		<%-- 
		<fieldset>
			<legend>object source</legend>
			<div>
				<asp:ObjectDataSource ID="ObjectDataSource_Movie" runat="server"
					TypeName="MovieCollection" 
					SelectMethod="GetMovies">
				</asp:ObjectDataSource>

				<asp:GridView ID="GridView_Movie" runat="server"
					 DataSourceID="ObjectDataSource_Movie">
				</asp:GridView>
			</div>
		</fieldset>

		<fieldset>
			<legend>Pulling all rows</legend>
			<asp:GridView ID="GridView_EmpData" runat="server"
				DataSourceID="ObjectDataSource_AllEmpData">
			</asp:GridView>

			<asp:ObjectDataSource ID="ObjectDataSource_AllEmpData" runat="server"
				  TypeName="EmpData"
				  SelectMethod="GetAllRecords">
			</asp:ObjectDataSource>
		</fieldset>

		<fieldset>
			<legend>Pulling paged rows</legend>

			<asp:GridView ID="GridView_PagedEmpData" runat="server"
				 DataSourceID="ObjectDataSource_PagedEmpData" AllowPaging="True" PageSize="10">
			</asp:GridView>

			<asp:ObjectDataSource ID="ObjectDataSource_PagedEmpData" runat="server"
				 TypeName="EmpData" SelectMethod="GetPagedRecords" 
				 SelectCountMethod="GetRecordCount" EnablePaging="True">
			</asp:ObjectDataSource>
		</fieldset>
		--%>
		<%--
		<fieldset>
			<legend>Sir's datasource paging demo</legend>

			<asp:ObjectDataSource ID="ObjectDataSource1" runat="server"
				 SelectMethod="GetEmpDetails" SelectCountMethod="GetEmpCount"
				 TypeName="DataLayer" UpdateMethod="UpdateEmp" EnablePaging="true">
				 <UpdateParameters>
					 <asp:Parameter Name="id" Type="Int32" />
					 <asp:Parameter Name="name" Type="String" />
					 <asp:Parameter Name="address" Type="String" />
				 </UpdateParameters>
			</asp:ObjectDataSource>			 
			 
			<asp:GridView ID="GridView1" runat="server" AutoGenerateEditButton="True"
				DataSourceID="ObjectDataSource1" AllowPaging="true" PageSize="2">
			 </asp:GridView>

			 <asp:Label ID="Label1" runat="server" Text=""></asp:Label>
		</fieldset>
		--%> <%-- 
		<fieldset>
			<legend>DS paging & sorting</legend>

			<asp:GridView ID="GridView_EmpPagedAndSorted" runat="server"
				 AllowPaging="true" AllowSorting="true" PageSize="7" 
				 DataSourceID="ObjectDataSource_EmpPagedAndSorted">
			</asp:GridView>

			<asp:ObjectDataSource ID="ObjectDataSource_EmpPagedAndSorted" runat="server"
				 EnablePaging="true" TypeName="EmpData" SelectMethod="GetPagedSortedRecords" 
				 SelectCountMethod="GetRecordCount" SortParameterName="sortExpression">
			</asp:ObjectDataSource>
		</fieldset>
		--%>
		<fieldset>
			<legend>CRUD operations on employees</legend>

			<asp:GridView ID="GridView_EmpDataCRUDOperations" runat="server"
				 AllowPaging="True" AllowSorting="True" PageSize="5" 				 
				 AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
				 DataKeyNames="id" DataSourceID="ObjectDataSource_EmpDataCRUDOperations">
				<EmptyDataTemplate>
					<asp:Label ID="Label1" runat="server" Text="No data found!"></asp:Label>
				</EmptyDataTemplate>
			</asp:GridView>
			
			<asp:ObjectDataSource ID="ObjectDataSource_EmpDataCRUDOperations" runat="server"
				 EnablePaging="true" TypeName="EmpData" SelectMethod="GetPagedSortedRecords" 
				 SelectCountMethod="GetRecordCount" SortParameterName="sortExpression"
				 InsertMethod="Insert" UpdateMethod="Update" DeleteMethod="Delete">
				 <UpdateParameters>
					<asp:Parameter Name="id" Type="Int32" />
					<asp:Parameter Name="name" Type="String" />
					<asp:Parameter Name="address" Type="String" />
				 </UpdateParameters>
				 <DeleteParameters>
					<asp:Parameter Name="id" Type="Int32" />
				 </DeleteParameters>
			</asp:ObjectDataSource>

		</fieldset>

		
		<fieldset>
			<legend>Add new employee</legend>

			<asp:DetailsView ID="DetailsView_EmpDataCRUDOperations" runat="server" 
				Height="50px" Width="125px"
				DataSourceID="ObjectDataSource_EmpDataCRUDOperations"
				DefaultMode="Insert" >
				<Fields>					
					<asp:BoundField DataField="name" HeaderText="Name" />
					<asp:BoundField DataField="address" HeaderText="Address" />
					<asp:CommandField ShowInsertButton="true" />
				</Fields>
			</asp:DetailsView>

		</fieldset>
    </form>
	</body>
</html>
