<%@ Page Language="C#" AutoEventWireup="true" CodeFile="SqlDataSourceTest.aspx.cs" Inherits="SqlDataSourceTest" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>[Test] SqlDataSource</title>
	<link rel="stylesheet" type="text/css" href="~/Styles/custom.css" />
</head>
<body>
    <form id="form1" runat="server">
        <div class="content">
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
				ConnectionString="<%$ ConnectionStrings:constr_localdb %>" 
				SelectCommand="SELECT * FROM [employee]" 
				DeleteCommand="DELETE FROM [employee] WHERE [id] = @original_id AND (([name] = @original_name) OR ([name] IS NULL AND @original_name IS NULL)) AND (([dept_id] = @original_dept_id) OR ([dept_id] IS NULL AND @original_dept_id IS NULL))" 
				InsertCommand="INSERT INTO [employee] ([id], [name], [dept_id]) VALUES (@id, @name, @dept_id)" 
				
				UpdateCommand="UPDATE [employee] SET [name] = @name, [dept_id] = @dept_id WHERE [id] = @original_id AND (([name] = @original_name) OR ([name] IS NULL AND @original_name IS NULL)) AND (([dept_id] = @original_dept_id) OR ([dept_id] IS NULL AND @original_dept_id IS NULL))" 
				ConflictDetection="CompareAllValues" 
				OldValuesParameterFormatString="original_{0}" oninserted="SqlDataSource1_Inserted" 
				oninserting="SqlDataSource1_Inserting">
				<DeleteParameters>
					<asp:Parameter Name="original_id" Type="Int32" />
					<asp:Parameter Name="original_name" Type="String" />
					<asp:Parameter Name="original_dept_id" Type="Int32" />
				</DeleteParameters>
				<InsertParameters>				  
					<asp:ControlParameter ControlID="TextBox_Id" PropertyName="Text" Name="id" Type="Int32" />
					<asp:ControlParameter ControlID="TextBox_Name" PropertyName="Text" Name="name" Type="String" />
					<asp:ControlParameter ControlID="TextBox_DeptId" PropertyName="Text" Name="dept_id" Type="Int32" />
<%--
					<asp:Parameter Name="id" Type="Int32" />
					<asp:Parameter Name="name" Type="String" />
					<asp:Parameter Name="dept_id" Type="Int32" />
--%>
				</InsertParameters>
				<UpdateParameters>
					<asp:Parameter Name="name" Type="String" />
					<asp:Parameter Name="dept_id" Type="Int32" />
					<asp:Parameter Name="original_id" Type="Int32" />
					<asp:Parameter Name="original_name" Type="String" />
					<asp:Parameter Name="original_dept_id" Type="Int32" />
				</UpdateParameters>
			</asp:SqlDataSource>

			<asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
				AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
				AutoGenerateEditButton="True" Caption="Employee" CaptionAlign="Top" DataKeyNames="id" 
				DataSourceID="SqlDataSource1" PageSize="3" 
				ShowFooter="True">
				<Columns>
					<asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id" />
					<asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
					<asp:BoundField DataField="dept_id" HeaderText="dept_id" SortExpression="dept_id" />
				</Columns>
			</asp:GridView>
        </div>
		<div class="content">
			*id: <asp:TextBox ID="TextBox_Id" runat="server"></asp:TextBox> <br>
			name: <asp:TextBox ID="TextBox_Name" runat="server"></asp:TextBox> <br>
			*dept id: <asp:TextBox ID="TextBox_DeptId" runat="server"></asp:TextBox> <br>
			<asp:Button ID="Button_Insert" runat="server" Text="Insert" 
				onclick="Button_Insert_Click" /> <br>
			* should not inserted manually!!
		</div>
    </form>
</body>
</html>
