<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Information.aspx.cs" Inherits="Information" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Bank information</title>
	<link rel="stylesheet" type="text/css" href="~/Styles/custom.css" />
</head>
<body>	
	<form id="form1" runat="server">
	<div>
		<asp:Menu ID="Menu_PageNavigation" runat="server" BackColor="#B5C7DE" 
			DynamicHorizontalOffset="2" Font-Names="Verdana" Font-Size="Small" 
			ForeColor="#284E98" onmenuitemclick="Menu_PageNavigation_MenuItemClick" 
			Orientation="Horizontal" StaticSubMenuIndent="10px">
			<DynamicHoverStyle BackColor="#284E98" ForeColor="White" />
			<DynamicMenuItemStyle HorizontalPadding="5px" VerticalPadding="2px" />
			<DynamicMenuStyle BackColor="#B5C7DE" />
			<DynamicSelectedStyle BackColor="#507CD1" />
			<Items>
				<asp:MenuItem Text="Customers" Value="Customers"></asp:MenuItem>
				<asp:MenuItem Text="Loans" Value="Loans"></asp:MenuItem>
				<asp:MenuItem Text="Information" Value="Information" Selected="True"></asp:MenuItem>
			</Items>
			<StaticHoverStyle BackColor="#284E98" ForeColor="White" />
			<StaticMenuItemStyle HorizontalPadding="5px" VerticalPadding="2px" />
			<StaticSelectedStyle BackColor="#507CD1" />
		</asp:Menu>
	</div>
	<br/>
	<div class="sidebar">
		<asp:Menu ID="Menu_Views" runat="server" 
			BackColor="#FFFBD6" DynamicHorizontalOffset="2" Font-Names="Verdana" 
			Font-Size="Small" ForeColor="#990000" StaticSubMenuIndent="10px" 
			onmenuitemclick="Menu_Views_MenuItemClick">
			<DynamicHoverStyle BackColor="#990000" ForeColor="White" />
			<DynamicMenuItemStyle HorizontalPadding="5px" VerticalPadding="2px" />
			<DynamicMenuStyle BackColor="#FFFBD6" />
			<DynamicSelectedStyle BackColor="#FFCC66" />
			<Items>
				<asp:MenuItem Text="Customer" Value="0" Selected="True"></asp:MenuItem>
				<asp:MenuItem Text="Branch" Value="1"></asp:MenuItem>
				<asp:MenuItem Text="Loan" Value="2"></asp:MenuItem>
				<asp:MenuItem Text="Borrower" Value="3"></asp:MenuItem>
				<asp:MenuItem Text="Payment" Value="4"></asp:MenuItem>
			</Items>
			<StaticHoverStyle BackColor="#990000" ForeColor="White" />
			<StaticMenuItemStyle HorizontalPadding="5px" VerticalPadding="2px" />
			<StaticSelectedStyle BackColor="#FFCC66" />
		</asp:Menu>
	</div>

	<div class="multiview">
		<asp:MultiView ID="MultiView_Information" ActiveViewIndex="0" runat="server">
			<asp:View ID="View_Customer" runat="server">
				<h2>Customer information</h2>

				<asp:ObjectDataSource ID="ObjectDataSource_Customers" runat="server"
						EnablePaging="true" TypeName="DbOperations.CustomerData"
						SelectMethod="GetPagedSortedDataRows" SelectCountMethod="GetDataRowCount"
						SortParameterName="sortExpression"
						InsertMethod="Insert" UpdateMethod="Update" DeleteMethod="Delete">
					<UpdateParameters>
						<asp:Parameter Name="id" Type="Int32" />
						<asp:Parameter Name="name" Type="String" />
						<asp:Parameter Name="street" Type="String" />
						<asp:Parameter Name="city" Type="String" />
					</UpdateParameters>
					<DeleteParameters>
						<asp:Parameter Name="id" Type="Int32" />
					</DeleteParameters>
				</asp:ObjectDataSource>

				<fieldset>
					<legend>Records</legend>
					<asp:GridView ID="GridView_Customers" runat="server"
							 AllowPaging="True" AllowSorting="True" PageSize="5" 				 
							 AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
							 DataSourceID="ObjectDataSource_Customers" DataKeyNames="id">
						<EmptyDataTemplate>
							<asp:Label ID="Label1" runat="server" Text="No data found!"></asp:Label>
						</EmptyDataTemplate>
					</asp:GridView>
				</fieldset>
				<fieldset>
					<legend>Add new</legend>
					<asp:DetailsView ID="DetailsView_NewCustomer" runat="server" 
							Height="50px" Width="125px"
							DataSourceID="ObjectDataSource_Customers"
							DefaultMode="Insert" DataKeyNames="id">
						<Fields>
							<asp:BoundField DataField="name" HeaderText="Name" />
							<asp:BoundField DataField="street" HeaderText="Street" />
							<asp:BoundField DataField="city" HeaderText="City" />
							<asp:CommandField ShowInsertButton="true" />
						</Fields>
					</asp:DetailsView>
				</fieldset>
			</asp:View>				

			<asp:View ID="View_Branches" runat="server">
				<h2>Branch Information</h2>

				<asp:ObjectDataSource ID="ObjectDataSource_Branches" runat="server"
						EnablePaging="true" TypeName="DbOperations.BranchData" 
						SelectMethod="GetPagedSortedRecords" SelectCountMethod="GetRecordCount"
						SortParameterName="sortExpression"
						InsertMethod="Insert" UpdateMethod="Update" DeleteMethod="Delete">
					<UpdateParameters>
						<asp:Parameter Name="name" Type="String" />
						<asp:Parameter Name="city" Type="String" />
						<asp:Parameter Name="assets" Type="Int32" />
					</UpdateParameters>
					<DeleteParameters>
						<asp:Parameter Name="name" Type="String" />
						<asp:Parameter Name="city" Type="String" />
					</DeleteParameters>
				</asp:ObjectDataSource>

				<fieldset>
					<legend>Records</legend>
					<asp:GridView ID="GridView_Branches" runat="server"
							 AllowPaging="True" AllowSorting="True" PageSize="5" 				 
							 AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
							 DataSourceID="ObjectDataSource_Branches" DataKeyNames="name,city">
						<EmptyDataTemplate>
							<asp:Label ID="Label1" runat="server" Text="No data found!"></asp:Label>
						</EmptyDataTemplate>
					</asp:GridView>
				</fieldset>
				<fieldset>
					<legend>Add new</legend>
					<asp:DetailsView ID="DetailsView_NewBranch" runat="server" 
							Height="50px" Width="125px"
							DataSourceID="ObjectDataSource_Branches"
							DefaultMode="Insert" DataKeyNames="name,city">
						<Fields>
							<asp:BoundField DataField="name" HeaderText="Name" />
							<asp:BoundField DataField="city" HeaderText="City" />
							<asp:BoundField DataField="assets" HeaderText="Assets" />
							<asp:CommandField ShowInsertButton="true" />
						</Fields>
					</asp:DetailsView>
				</fieldset>
			</asp:View>

			<asp:View ID="View_Loan" runat="server">
				<h2>Loan Information</h2>
				
				<asp:ObjectDataSource ID="ObjectDataSource_Loans" runat="server"
						EnablePaging="true" TypeName="DbOperations.LoanData" 
						SelectMethod="GetPagedSortedRecords" SelectCountMethod="GetRecordCount"
						SortParameterName="sortExpression"
						InsertMethod="Insert" DeleteMethod="Delete">
					<DeleteParameters>
						<asp:Parameter Name="number" Type="Int32" />
						<asp:Parameter Name="amount" Type="Int32" />
						<asp:Parameter Name="branch_name" Type="String" />
						<asp:Parameter Name="customer_id" Type="Int32" />
					</DeleteParameters>
				</asp:ObjectDataSource>

				<fieldset>
					<legend>Records</legend>
					<asp:GridView ID="GridView_Loans" runat="server"
							 AllowPaging="True" AllowSorting="True" PageSize="5"
							 DataSourceID="ObjectDataSource_Loans" 
							 AutoGenerateDeleteButton="True" DataKeyNames="number">
						<EmptyDataTemplate>
							<asp:Label ID="Label1" runat="server" Text="No data found!"></asp:Label>
						</EmptyDataTemplate>
					</asp:GridView>
				</fieldset>
				<fieldset>
					<legend>Add new</legend>
					<asp:DetailsView ID="DetailsView_NewLoan" runat="server" 
							Height="50px" Width="125px"
							DataSourceID="ObjectDataSource_Loans"
							DefaultMode="Insert" 
							DataKeyNames="number">
						<Fields>
							<asp:BoundField DataField="amount" HeaderText="Amount" />
							<asp:BoundField DataField="branch_name" HeaderText="Branch name" />
							<asp:BoundField DataField="customer_id" HeaderText="Customer ID" />
							<asp:CommandField ShowInsertButton="true" />
						</Fields>
					</asp:DetailsView>
				</fieldset>
			</asp:View>

			<asp:View ID="View_Borrowers" runat="server">
				<h2>Borrower Information</h2>

				<asp:ObjectDataSource ID="ObjectDataSource_Borrowers" runat="server"
						TypeName="DbOperations.BorrowerData" 
						SelectMethod="GetRecords" SelectCountMethod="GetRecordCount">
				</asp:ObjectDataSource>

				<fieldset>
					<legend>Records</legend>
					<asp:GridView ID="GridView_Borrowers" runat="server"
							 DataSourceID="ObjectDataSource_Borrowers">
						<EmptyDataTemplate>
							<asp:Label ID="Label1" runat="server" Text="No data found!"></asp:Label>
						</EmptyDataTemplate>
					</asp:GridView>
				</fieldset>
			</asp:View>

			<asp:View ID="View_Payments" runat="server">
				<h2>Payment Information</h2>

				<asp:ObjectDataSource ID="ObjectDataSource_Payments" runat="server"
						EnablePaging="true" TypeName="DbOperations.PaymentData" 
						SelectMethod="GetPagedSortedRecords" SelectCountMethod="GetRecordCount"
						SortParameterName="sortExpression">
				</asp:ObjectDataSource>

				<fieldset>
					<legend>Records</legend>
					<asp:GridView ID="GridView_Payments" runat="server"
							 AllowPaging="True" AllowSorting="True" PageSize="5"
							 DataSourceID="ObjectDataSource_Payments">
						<EmptyDataTemplate>
							<asp:Label ID="Label1" runat="server" Text="No data found!"></asp:Label>
						</EmptyDataTemplate>
					</asp:GridView>
				</fieldset>
			</asp:View>
		</asp:MultiView>
	</div>
    </form>
</body>
</html>
